services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_db_dev:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    depends_on:
      - postgres
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app/src:/api/app/src

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:  
  postgres_db_dev: