name: dart_web_startup_sl8s
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.8.1"
  flutter: ">=3.32.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  library_architecture_mvvm_modify: ^6.1.2
  meta: ^1.15.0
  intl: ^0.20.2
  responsive_framework: ^1.5.1
  go_router: ^15.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.14

flutter:
  assets:
    - assets/icons/app_icon.ico
    - assets/icons/app_icon.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_18pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_24pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_28pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_18pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_24pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_28pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_18pt_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_24pt_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_28pt_regular.ttf
          weight: 400
  uses-material-design: true
  generate: true