name: typescript_discord_bot_startup_sl8s-running_unit_tests
run-name: ${{ github.actor }} - typescript_discord_bot_startup_sl8s-running_unit_tests
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  node_version: 22.15.0
  working_directory: typescript_discord_bot_startup_sl8s/app
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
      - run: npm run download
        working-directory: ${{ env.working_directory }}
      - run: npm run tests
        working-directory: ${{ env.working_directory }}
